### ISSUE TITLE
Fill out missing data on BNB

### ISSUE THREAD

**Issue by trmaphi** [Octan-Labs/pipeline#168]
- blocks
- transaction
- logs

**Comment by trmaphi** [comment]
10 connnection to clickhouse là lỗi

**Comment by noobmdev** [comment]
```
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - Traceback (most recent call last):
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     httplib_response = self._make_request(
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 466, in _make_request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     six.raise_from(e, None)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "<string>", line 3, in raise_from
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 461, in _make_request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     httplib_response = conn.getresponse()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     response.begin()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     version, status, reason = self._read_status()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     raise RemoteDisconnected("Remote end closed connection without"
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - http.client.RemoteDisconnected: Remote end closed connection without response
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - 
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - During handling of the above exception, another exception occurred:
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - 
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - Traceback (most recent call last):
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 404, in _raw_request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     response: HTTPResponse = self.http.request(method, url, **kwargs)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 78, in request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return self.request_encode_body(
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/request.py", line 170, in request_encode_body
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return self.urlopen(method, url, **extra_kw)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 376, in urlopen
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     response = conn.urlopen(method, u.request_uri, **kw)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     retries = retries.increment(
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     raise six.reraise(type(error), error, _stacktrace)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     raise value.with_traceback(tb)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     httplib_response = self._make_request(
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 466, in _make_request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     six.raise_from(e, None)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "<string>", line 3, in raise_from
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 461, in _make_request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     httplib_response = conn.getresponse()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     response.begin()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     version, status, reason = self._read_status()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     raise RemoteDisconnected("Remote end closed connection without"
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - 
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - The above exception was the direct cause of the following exception:
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - 
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - Traceback (most recent call last):
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return _run_code(code, main_globals, None,
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     exec(code, run_globals)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/ethereum-etl/ethereumetl/__main__.py", line 26, in <module>
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     cli()
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return self.main(*args, **kwargs)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     rv = self.invoke(ctx)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return __callback(*args, **kwargs)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/ethereum-etl/ethereumetl/cli/export_all.py", line 58, in export_all
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     export_all_common(get_partitions(start, end, partition_batch_size, provider_uri, worker_job_index, first_worker_partition_index, partition_to_hour),
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/ethereum-etl/ethereumetl/jobs/export_all_common.py", line 78, in export_all_common
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     streamer_adapter.export_all(start_block, end_block)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/ethereum-etl/ethereumetl/streaming/eth_streamer_adapter.py", line 59, in export_all
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     self._calculate_offset_and_export(sort_by(enriched_transactions, ('block_number', 'transaction_index')))
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/ethereum-etl/ethereumetl/streaming/eth_streamer_adapter.py", line 145, in _calculate_offset_and_export
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     self.item_exporter.export_items(items)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/ethereum-etl/blockchainetl/jobs/exporters/clickhouse_item_exporter.py", line 78, in export_items
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     self.connection.insert(table, data=table_data, column_names=self.tables[table].column_names,
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/client.py", line 554, in insert
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     return self.data_insert(context)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 251, in data_insert
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     response = self._raw_request(block_gen, params, headers, error_handler=error_handler, server_wait=False)
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -   File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 415, in _raw_request
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO -     raise OperationalError(f'Error {ex} executing HTTP request attempt {attempts} {self.url}') from ex
[2023-09-19, 03:26:39 GMT] {pod_manager.py:367} INFO - clickhouse_connect.driver.exceptions.OperationalError: Error ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) executing HTTP request attempt 0 https://oaf19hxze9.asia-southeast1.gcp.clickhouse.cloud:8443/
```
